# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Basic日本' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

  # Pods for Basic日本
  pod 'MessageKit'
  
  target 'Basic日本Tests' do
    # Pods for testing
  end

  target 'Basic日本UITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
